#!/bin/bash

#file=simplemc
file=1_functions4FittingTae
#file=gibbs

#OPENMPFLAGS=-fopenmp
#PKG_CPPFLAGS="$(RCPPFLAGS) $(RCPPINCL) $(OPENMPFLAGS)" 
#PKG_LIBS="$(RLDFLAGS) $(RCPPLIBS) $(OPENMPFLAGS)"

#PKG_CPPFLAGS="-fopenmp" 
#PKG_LIBS="-fopenmp"
#R CMD SHLIB $file.R
R CMD BATCH $file.R
cat $file.Rout

#PKG_CXXFLAGS=`Rscript -e 'Rcpp:::CxxFlags()'` \
#PKG_LIBS=`Rscript -e 'Rcpp:::LdFlags()'`  \
#R CMD SHLIB test.cpp
